# Generated by Django 4.2.4 on 2023-08-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Article2',
        ),
    ]
